name: Maven Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '22'

      - name: Run Maven Tests
        run: mvn clean test -Dsurefire.version=3.0.0-M5 -Dtest=**/*Test -DfailIfNoTests=false
